trigger:
- master

jobs:
- job: BuildandPush
  displayName: 'BuildandPush'
  pool:
    vmImage: 'ubuntu-16.04'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'ls'
    - task: Docker@2
      displayName: Build image
      inputs:
        containerRegistry: 'tma-acr-connection'
        repository: 'dotnetcore'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'







