- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build job
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - script:  |
        docker build -t $(dockerId)/dotnetcore . 






