trigger:
- master

jobs:
- job: windows
  displayName: 'Windows'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - task: Bash@3
      inputs:
      targetType: 'inline'
      script: 'echo "Test"'







