# Starter pipeline
- task: Docker@2
  inputs:
    containerRegistry: 'tma-acr-connection'
    repository: 'dotnetcore'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Set variables once
variables:
  imageName: dotnetcore
  dockerId:  tmaregistry.azurecr.io

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04' # other options: 'macOS-10.13', 'vs2017-win2016'

steps:
- script: docker build -t $(dockerId)/$(imageName) .  # add options to this command to meet your needs






